server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka

zuul:
  prefix: /api
  ignored-services: "*"
  routes:
    products:
      path: /**
      service-id: products_service
      strip-prefix: false
      custom-sensitive-headers: true
    authentication_service:
      path: /auth/**
      service-id: authentication_service
      strip-prefix: false
      custom-sensitive-headers: true
