server:
  port: 8082
spring:
  application:
    name: sale_service
  datasource:
    url: jdbc:h2:mem:testdb
  username: sa
  password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
security:
  jwt:
    token:
      secret-key: chave_microservices
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka